web:
   image: tutum/apache-php
   environment:
     - ALLOW_OVERRIDE=true
   ports:
     - "8080:80"
   links:
     - db
   volumes:
     - ./:/app

db:
  image: mariadb
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: hidden1234
    MYSQL_DATABASE: MyDB

phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: hidden1234